# Generated by Django 4.2.5 on 2023-09-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PN", "PENDING"), ("PD", "PAID")], max_length=2
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("P", "PAYMENT"), ("F", "FINE")], max_length=1
                    ),
                ),
                ("borrowing_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
                ("session_url", models.URLField()),
                ("session_id", models.CharField(max_length=255)),
                ("money_to_pay", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
