# Generated by Django 4.2.5 on 2023-09-21 10:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("borrowing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="is_paid",
        ),
    ]
