# Generated by Django 4.2.5 on 2023-09-20 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("author", models.CharField(max_length=255)),
                (
                    "cover",
                    models.CharField(
                        choices=[("H", "HARD"), ("S", "SOFT")], max_length=1
                    ),
                ),
                (
                    "inventory",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ]
                    ),
                ),
                ("daily_fee", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
